name: alpaca_dart
description: Dart wrapper for the Alpaca REST API.
version: 0.0.1
author: Matthew Cliatt <matthewcliatt@gmail.com>
homepage: https://github.com/mtcliatt/alpaca-dart
repository: https://github.com/mtcliatt/alpaca-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  mockito: ^4.0.0

dev_dependencies:
  test: ^1.0.0
