name: alpaca_dart
description: Dart wrapper for the Alpaca REST API.
# version: 1.0.0
# author: mtcliatt <matthewcliatt@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  mockito: ^4.0.0

dev_dependencies:
  test: ^1.0.0
