name: alpaca_dart
description: A Dart wrapper for the Alpaca REST API (alpaca.markets).
version: 0.0.1
author: Matthew Cliatt <matthewcliatt@gmail.com>
homepage: https://github.com/mtcliatt/alpaca-dart
repository: https://github.com/mtcliatt/alpaca-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0+1
  mockito: ^4.0.0

dev_dependencies:
  test: ^1.0.0
